Feature/category/img fix(재재수정)
SpringProject24/FoodieTree_frontend pull request #38
Opened 2024-07-26 06:44 UTC by hyerin11

## 개요

- 이미지 경로 수정
- 남은 수량 추가
- 카테고리 별 이동 페이지(scss 반응형 적용)
- host-config 적용

## PR 유형

## 작업사항
- 

## 변경로직

2024-07-26 07:51 UTC, hoseong511 requested changes
internal server error 가 발생해서 작업 사항을 확인할 수 없었습니다.

다시 한 번 확인부탁드려요

2024-07-26 07:51 UTC, hoseong511 commented on src/pages/userMain/MainPage.js
> +    fetch(STORELISTS_URL)
<img width="1313" alt="image" src="https://github.com/user-attachments/assets/1ce45296-4777-47ba-a39c-40d5d7a4c084">

해당 라우터로 요청을 보냈을 때의 서버 쪽 로그입니다. 메인 브랜치에서 서버를 실행한 상태입니다.

2024-07-26 08:25 UTC, hyerin11 commented on src/pages/userMain/MainPage.js
> +    fetch(STORELISTS_URL)
앗 지금 price가 null값이 들어와서 그런 것 같은데, db에서 price가 null인 row 지우고 나니까 잘 되는 것 같습니다.
추가로 poductCnt에도 null이 들어갈 경우에도 같은 에러가 발생하면서 실행되지 않는데,
지금은 db에서  null 지운 상태라 다시 한번 확인해주실 수 있나요?

2024-07-27 05:41 UTC, hoseong511 reviewed
서버 쪽 코드도 살펴보셔야 할 것 같아요!

아래 코멘트 확인해주세요~ 그리고 현재 공용 디비를 테스트용으로 사용하고 있어서 store 테이블에 레코드들에 null 이 포함될 수 있으므로 되도록 참조 자료형(Integer, Long, ...)들을 사용해서 null pointer exception 이 일어나지 않게 처리해주시면 좋을 것 같습니다.

#### ***코멘트들 확인해보시고 보완한 커밋을 남기신 후 현재 이 브랜치로 푸쉬하셔서 작업 마무리 해주세요***

2024-07-27 05:41 UTC, hoseong511 commented on src/components/mainPage/BestStoreList.js
> +                  <img src={store.storeImg} alt={store.storeName} />
```suggestion
                  <img src={store.storeImage} alt={store.storeName} />
```

2024-07-27 05:41 UTC, hoseong511 commented on src/components/mainPage/CategoryList.js
> +            <img src={store.storeImg} alt={store.storeName} className={styles.categoryImage} />
```suggestion
            <img src={store.storeImage} alt={store.storeName} className={styles.categoryImage} />
```

2024-07-27 05:41 UTC, hoseong511 commented on src/components/mainPage/FoodNav.js
> +                <img src={store.storeImg} alt={store.storeName} />
```suggestion
                <img src={store.storeImage} alt={store.storeName} />
```

2024-07-27 05:41 UTC, hoseong511 commented on src/components/mainPage/BestStoreList.js
> +                  <img src={store.storeImg} alt={store.storeName} />
서버에 Store 엔터티에 `storeImage` 필드의 컬럼 애노테이션에 `store_image`로 되어있어서 `store_img`로 수정했습니다.
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/b0cad9de-b8ce-4c2b-a3e2-b852665dcf70">

서버에서 내려받는 데이터에 `storeImage` 로 되어있어서 img 태그에 모든 `storeImg`를 바꾸었더니 이미지가 잘 나왔습니다.

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/c665e45e-8acf-4154-a84a-27b5fd10a2f0">

2024-07-28 09:02 UTC, hyerin11 commented
제가 확인이 늦었ㄴ네요.
우선 제가 정확히 이해한 것인지는 모르겠는데,
이미지가 나오지 않는 문제에 대해 목요일에 바꾼 것이

1. **store엔터티 변경**
store 테이블에서 이미지가 store_img라 storeImg로 변경. (이전 프로젝트 엔터티에서는 storeImage로 되어 있었음.)
@Column(name = "store_img")
    private String storeImg; // 가게 사진
2. **FoodNav/BestStoreList에서 이미지 storeImg로 변경**

>>**문제 발생**<< price, productCnt에 null값 들어가면 오류 뜸
int -> Integer로 변경  (private Integer price; // 가격)  >>>아직 pr안올림(윗 문제 해결되면 올리려고 했음)

-------------
이렇게 해서 저는 이미지가 잘 나오는 상황이였는데, 
store 엔터티를 나래님께서도 사용하시는데 이때 storeImage로 되어 있으니
다시 이미지가 안나오기 시작했고,

따라서  storeImg를 storeImage로 다시 바꿔야 한다.

제가 이해한 것이 맞나요??

2024-07-28 15:00 UTC, hoseong511 approved these changes
서버 쪽 코드를 업데이트 하지 않고 테스트를 했던 제 잘못입니다..

고생하셨습니다

2024-07-28 15:18 UTC, merged